name: Automated deployment to GCR

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

jobs: 
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t habit .

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker tag habit ${{ secrets.DOCKER_USERNAME }}/habitstacker:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/habitstacker:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-push-image

    steps:
      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CRED }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'habitstacker'
          region: us-west1
          image: 'docker.io/${{ secrets.DOCKER_USERNAME }}/habitstacker:${{ github.sha }}'
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}
            TOKEN_SECRET=${{secrets.TOKEN_SECRET}}
