name: deploy api to GCR

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

jobs: 
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t habit .
      
      - name: retag Docker Image
        run: docker tag habit anorquist/habitstacker:v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Push Docker image 
        run: docker push anorquist/habitstacker:v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CRED }}'

      - name: Deploy to Cloud Run
        id: deploy
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: 'habitstacker'
          region: us-west1
          image: 'docker.io/${{ secrets.DOCKER_USERNAME }}/habitstacker:v3'